server:
  port: 8080

spring:
  datasource:
    password: root2
    url: jdbc:mysql://localhost:3307/gp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wang.gp.pojo